#!/bin/sh

BASEDIR=$(dirname $0)
JOB=$1
LISP=$2

echo "$JOB"ing "$LISP"...

# determine how to load/execute a single file in the given lisp.
if [ "$LISP" = "sbcl" ]
then
    EVAL_FILE="sbcl --noinform --non-interactive --load "
fi

if [ "$LISP" = "ccl" ]
then
    EVAL_FILE="ccl -b -Q -l"
fi

# compiling cl-mpi in parallel from many images may lead to errors, so I do a
# serial compilation run first.
mpiexec -npernode 1 $EVAL_FILE "$BASEDIR/load-cl-mpi.lisp"

if [ "$JOB" = "test" ]
then
    mpiexec -npernode 4 $EVAL_FILE "$BASEDIR/test-cl-mpi.lisp"
fi

if [ "$JOB" = "benchmark" ]
then
    mpiexec -npernode 2 $EVAL_FILE "$BASEDIR/benchmark-cl-mpi.lisp"
fi
