;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-
(include "mpi.h")

(in-package :mpi)

(constant (MPI_VERSION "MPI_VERSION"))
(constant (MPI_SUBVERSION "MPI_SUBVERSION"))


#-openmpi
(progn
  (constantenum (MPI_Errhandler :define-constants t)
                ((:MPI_ERRORS_RETURN "MPI_ERRORS_RETURN"))
                ((:MPI_ERRORS_ARE_FATAL "MPI_ERRORS_ARE_FATAL"))
                )

  (constantenum (MPI_Group :define-constants t)
                ((:MPI_GROUP_EMPTY "MPI_GROUP_EMPTY"))
                ((:MPI_GROUP_NULL  "MPI_GROUP_NULL"))
                )

  (constantenum (MPI_Comm :define-constants t)
                ((:MPI_COMM_WORLD "MPI_COMM_WORLD"))
                ((:MPI_COMM_SELF  "MPI_COMM_SELF"))
                ((:MPI_COMM_NULL  "MPI_COMM_NULL"))
                )

  (constantenum (MPI_Datatype :define-constants t)
                ((:MPI_DATATYPE_NULL "MPI_DATATYPE_NULL"))
                ((:MPI_LB "MPI_LB"))
                ((:MPI_UB "MPI_UB"))
                ((:MPI_CHAR "MPI_CHAR"))
                ((:MPI_SIGNED_CHAR "MPI_SIGNED_CHAR"))
                ((:MPI_UNSIGNED_CHAR "MPI_UNSIGNED_CHAR"))
                ((:MPI_BYTE "MPI_BYTE"))
                ((:MPI_SHORT "MPI_SHORT"))
                ((:MPI_UNSIGNED_SHORT "MPI_UNSIGNED_SHORT"))
                ((:MPI_INT "MPI_INT"))
                ((:MPI_UNSIGNED "MPI_UNSIGNED"))
                ((:MPI_LONG "MPI_LONG"))
                ((:MPI_UNSIGNED_LONG "MPI_UNSIGNED_LONG"))
                ((:MPI_LONG_LONG_INT "MPI_LONG_LONG_INT"))
                ((:MPI_UNSIGNED_LONG_LONG "MPI_UNSIGNED_LONG_LONG"))
                ((:MPI_FLOAT "MPI_FLOAT"))
                ((:MPI_DOUBLE "MPI_DOUBLE"))
                ((:MPI_LONG_DOUBLE "MPI_LONG_DOUBLE"))
                ((:MPI_WCHAR "MPI_WCHAR"))
                ((:MPI_PACKED "MPI_PACKED"))
                )

  (constantenum (MPI_Op :define-constants t)
                ((:MPI_NULL "MPI_NULL") :optional t)
                ((:MPI_MIN "MPI_MIN"))
                ((:MPI_MAX "MPI_MAX"))
                ((:MPI_SUM "MPI_SUM"))
                ((:MPI_PROD "MPI_PROD"))
                ((:MPI_LAND "MPI_LAND"))
                ((:MPI_BAND "MPI_BAND"))
                ((:MPI_LOR "MPI_LOR"))
                ((:MPI_BOR "MPI_BOR"))
                ((:MPI_LXOR "MPI_LXOR"))
                ((:MPI_BXOR "MPI_BXOR"))
                ((:MPI_MAXLOC "MPI_MAXLOC"))
                ((:MPI_MINLOC "MPI_MINLOC"))
                ((:MPI_REPLACE "MPI_REPLACE"))
                ((:MPI_NO_OP "MPI_NO_OP") :optional t)
                )
  )

;;; error constants
(constantenum (MPI_Error :define-constants t)
              ((:MPI_SUCCESS "MPI_SUCCESS"))
              ((:MPI_ERR_LASTCODE "MPI_ERR_LASTCODE"))
              ((:MPI_ERR_BUFFER "MPI_ERR_BUFFER") :optional t)
              ((:MPI_ERR_COUNT "MPI_ERR_COUNT") :optional t)
              ((:MPI_ERR_TYPE "MPI_ERR_TYPE") :optional t)
              ((:MPI_ERR_TAG "MPI_ERR_TAG") :optional t)
              ((:MPI_ERR_COMM "MPI_ERR_COMM") :optional t)
              ((:MPI_ERR_RANK "MPI_ERR_RANK") :optional t)
              ((:MPI_ERR_REQUEST "MPI_ERR_REQUEST") :optional t)
              ((:MPI_ERR_ROOT "MPI_ERR_ROOT") :optional t)
              ((:MPI_ERR_GROUP "MPI_ERR_GROUP") :optional t)
              ((:MPI_ERR_OP "MPI_ERR_OP") :optional t)
              ((:MPI_ERR_TOPOLOGY "MPI_ERR_TOPOLOGY") :optional t)
              ((:MPI_ERR_DIMS "MPI_ERR_DIMS") :optional t)
              ((:MPI_ERR_ARG "MPI_ERR_ARG") :optional t)
              ((:MPI_ERR_UNKNOWN "MPI_ERR_UNKNOWN") :optional t)
              ((:MPI_ERR_TRUNCATE "MPI_ERR_TRUNCATE") :optional t)
              ((:MPI_ERR_OTHER "MPI_ERR_OTHER") :optional t)
              ((:MPI_ERR_INTERN "MPI_ERR_INTERN") :optional t)
              ((:MPI_ERR_IN_STATUS "MPI_ERR_IN_STATUS") :optional t)
              ((:MPI_ERR_PENDING "MPI_ERR_PENDING") :optional t)
              ((:MPI_ERR_ACCESS "MPI_ERR_ACCESS") :optional t)
              ((:MPI_ERR_AMODE "MPI_ERR_AMODE") :optional t)
              ((:MPI_ERR_ASSERT "MPI_ERR_ASSERT") :optional t)
              ((:MPI_ERR_BAD_FILE "MPI_ERR_BAD_FILE") :optional t)
              ((:MPI_ERR_BASE "MPI_ERR_BASE") :optional t)
              ((:MPI_ERR_CONVERSION "MPI_ERR_CONVERSION") :optional t)
              ((:MPI_ERR_DISP "MPI_ERR_DISP") :optional t)
              ((:MPI_ERR_DUP_DATAREP "MPI_ERR_DUP_DATAREP") :optional t)
              ((:MPI_ERR_FILE_EXISTS "MPI_ERR_FILE_EXISTS") :optional t)
              ((:MPI_ERR_FILE_IN_USE "MPI_ERR_FILE_IN_USE") :optional t)
              ((:MPI_ERR_FILE "MPI_ERR_FILE") :optional t)
              ((:MPI_ERR_INFO_KEY "MPI_ERR_INFO_KEY") :optional t)
              ((:MPI_ERR_INFO_NOKEY "MPI_ERR_INFO_NOKEY") :optional t)
              ((:MPI_ERR_INFO_VALUE "MPI_ERR_INFO_VALUE") :optional t)
              ((:MPI_ERR_INFO "MPI_ERR_INFO") :optional t)
              ((:MPI_ERR_IO "MPI_ERR_IO") :optional t)
              ((:MPI_ERR_KEYVAL "MPI_ERR_KEYVAL") :optional t)
              ((:MPI_ERR_LOCKTYPE "MPI_ERR_LOCKTYPE") :optional t)
              ((:MPI_ERR_NAME "MPI_ERR_NAME") :optional t)
              ((:MPI_ERR_NO_MEM "MPI_ERR_NO_MEM") :optional t)
              ((:MPI_ERR_NOT_SAME "MPI_ERR_NOT_SAME") :optional t)
              ((:MPI_ERR_NO_SPACE "MPI_ERR_NO_SPACE") :optional t)
              ((:MPI_ERR_NO_SUCH_FILE "MPI_ERR_NO_SUCH_FILE") :optional t)
              ((:MPI_ERR_PORT "MPI_ERR_PORT") :optional t)
              ((:MPI_ERR_QUOTA "MPI_ERR_QUOTA") :optional t)
              ((:MPI_ERR_READ_ONLY "MPI_ERR_READ_ONLY") :optional t)
              ((:MPI_ERR_RMA_CONFLICT "MPI_ERR_RMA_CONFLICT") :optional t)
              ((:MPI_ERR_RMA_SYNC "MPI_ERR_RMA_SYNC") :optional t)
              ((:MPI_ERR_SERVICE "MPI_ERR_SERVICE") :optional t)
              ((:MPI_ERR_SIZE "MPI_ERR_SIZE") :optional t)
              ((:MPI_ERR_SPAWN "MPI_ERR_SPAWN") :optional t)
              ((:MPI_ERR_UNSUPPORTED_DATAREP "MPI_ERR_UNSUPPORTED_DATAREP") :optional t)
              ((:MPI_ERR_UNSUPPORTED_OPERATION "MPI_ERR_UNSUPPORTED_OPERATION") :optional t)
              ((:MPI_ERR_WIN "MPI_ERR_WIN") :optional t)
              ((:MPI_T_ERR_MEMORY "MPI_T_ERR_MEMORY") :optional t)
              ((:MPI_T_ERR_NOT_INITIALIZED "MPI_T_ERR_NOT_INITIALIZED") :optional t)
              ((:MPI_T_ERR_CANNOT_INIT "MPI_T_ERR_CANNOT_INIT") :optional t)
              ((:MPI_T_ERR_INVALID_INDEX "MPI_T_ERR_INVALID_INDEX") :optional t)
              ((:MPI_T_ERR_INVALID_ITEM "MPI_T_ERR_INVALID_ITEM") :optional t)
              ((:MPI_T_ERR_INVALID_HANDLE "MPI_T_ERR_INVALID_HANDLE") :optional t)
              ((:MPI_T_ERR_OUT_OF_HANDLES "MPI_T_ERR_OUT_OF_HANDLES") :optional t)
              ((:MPI_T_ERR_OUT_OF_SESSIONS "MPI_T_ERR_OUT_OF_SESSIONS") :optional t)
              ((:MPI_T_ERR_INVALID_SESSION "MPI_T_ERR_INVALID_SESSION") :optional t)
              ((:MPI_T_ERR_CVAR_SET_NOT_NOW "MPI_T_ERR_CVAR_SET_NOT_NOW") :optional t)
              ((:MPI_T_ERR_CVAR_SET_NEVER "MPI_T_ERR_CVAR_SET_NEVER") :optional t)
              ((:MPI_T_ERR_PVAR_NO_STARTSTOP "MPI_T_ERR_PVAR_NO_STARTSTOP") :optional t)
              ((:MPI_T_ERR_PVAR_NO_WRITE "MPI_T_ERR_PVAR_NO_WRITE") :optional t)
              ((:MPI_T_ERR_PVAR_NO_ATOMIC "MPI_T_ERR_PVAR_NO_ATOMIC") :optional t)
              ((:MPI_ERR_RMA_RANGE "MPI_ERR_RMA_RANGE") :optional t)
              ((:MPI_ERR_RMA_ATTACH "MPI_ERR_RMA_ATTACH") :optional t)
              ((:MPI_ERR_RMA_FLAVOR "MPI_ERR_RMA_FLAVOR") :optional t)
              ((:MPI_ERR_RMA_SHARED "MPI_ERR_RMA_SHARED") :optional t)
              ((:MPI_ERR_SYSRESOURCE "MPI_ERR_SYSRESOURCE") :optional t))

(constant (MPI_ANY_TAG "MPI_ANY_TAG"))
(constant (MPI_ANY_SOURCE "MPI_ANY_SOURCE"))

(constant (MPI_MAX_PROCESSOR_NAME "MPI_MAX_PROCESSOR_NAME"))
(constant (MPI_MAX_ERROR_STRING "MPI_MAX_ERROR_STRING"))

(cstruct MPI_Status "MPI_Status"
         (MPI_SOURCE "MPI_SOURCE" :type :int)
         (MPI_TAG "MPI_TAG" :type :int)
         (MPI_ERROR "MPI_ERROR" :type :int))
